CREATE TABLE PASSWORD (
  PASSWORD_ID INT                   NOT NULL AUTO_INCREMENT,
  HASH        VARCHAR(64)           NOT NULL,
  SALT        VARCHAR(64)           NOT NULL,
  DELETED     BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE PRICE (
  PRICE_ID INT                   NOT NULL AUTO_INCREMENT,
  VALUE    DECIMAL(20, 4)        NOT NULL,
  DELETED  BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE ROLE (
  ROLE_ID INT                    NOT NULL AUTO_INCREMENT,
  NAME    VARCHAR_IGNORECASE(32) NOT NULL,
  DELETED BOOLEAN DEFAULT FALSE  NOT NULL
);

CREATE TABLE IMAGE (
  IMAGE_ID      INT                   NOT NULL AUTO_INCREMENT,
  NAME          VARCHAR(128)          NOT NULL,
  CONTENT_TYPE  VARCHAR(32)           NOT NULL,
  CONTENT       BINARY                NOT NULL,
  LAST_MODIFIED TIMESTAMP(0)          NOT NULL,
  DELETED       BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE USER (
  USER_ID     INT                    NOT NULL AUTO_INCREMENT,
  NAME        VARCHAR(32)            NOT NULL,
  EMAIL       VARCHAR_IGNORECASE(64) NOT NULL,
  ROLE_ID     INT DEFAULT 1          NOT NULL,
  PASSWORD_ID INT                    NOT NULL,
  BANNED      BOOLEAN DEFAULT FALSE  NOT NULL,
  DELETED     BOOLEAN DEFAULT FALSE  NOT NULL
);

CREATE TABLE STATUS (
  STATUS_ID INT                    NOT NULL AUTO_INCREMENT,
  NAME      VARCHAR_IGNORECASE(32) NOT NULL,
  DELETED   BOOLEAN DEFAULT FALSE  NOT NULL
);

CREATE TABLE PRODUCT (
  PRODUCT_ID  INT           NOT NULL AUTO_INCREMENT,
  NAME        VARCHAR(128)  NOT NULL,
  CATEGORY_ID INT           NOT NULL,
  DESCRIPTION VARCHAR(1024) NOT NULL,
  PRICE_ID    INT           NOT NULL,
  IMAGE_ID    INT           NOT NULL,
  DELETED     BOOLEAN       NOT NULL
);

CREATE TABLE CATEGORY (
  CATEGORY_ID INT                     NOT NULL AUTO_INCREMENT,
  NAME        VARCHAR_IGNORECASE(128) NOT NULL,
  DELETED     BOOLEAN DEFAULT FALSE   NOT NULL
);

CREATE TABLE PURCHASE (
  PURCHASE_ID INT                   NOT NULL AUTO_INCREMENT,
  USER_ID     INT                   NOT NULL,
  PRODUCT_ID  INT                   NOT NULL,
  PRICE_ID    INT                   NOT NULL,
  DATE_ID     INT                   NOT NULL,
  STATUS_ID   INT DEFAULT 1         NOT NULL,
  DELETED     BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE DATE (
  DATE_ID INT                   NOT NULL AUTO_INCREMENT,
  TIME    BIGINT                NOT NULL,
  DELETED BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE ATTRIBUTE (
  ATTRIBUTE_ID  INT                   NOT NULL AUTO_INCREMENT,
  PRODUCT_ID    INT                   NOT NULL,
  NAME          VARCHAR(128)          NOT NULL,
  INTEGER_VALUE INT,
  DECIMAL_VALUE DECIMAL(20, 4),
  STRING_VALUE  VARCHAR(1024),
  DELETED       BOOLEAN DEFAULT FALSE NOT NULL
);

INSERT INTO ROLE (ROLE_ID, NAME, DELETED) VALUES
  (2, 'Admin', FALSE),
  (1, 'User', FALSE);

INSERT INTO STATUS (STATUS_ID, NAME, DELETED) VALUES
  (2, 'Paid', FALSE),
  (3, 'Canceled', FALSE),
  (1, 'Delivery', FALSE),
  (4, 'Unpaid', FALSE);

ALTER TABLE ATTRIBUTE ADD CONSTRAINT PK_ATTRIBUTE_ID PRIMARY KEY (ATTRIBUTE_ID);
ALTER TABLE ATTRIBUTE ADD CONSTRAINT FK_ATTRIBUTE_PRODUCT_ID FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID);
ALTER TABLE CATEGORY ADD CONSTRAINT PK_CATEGORY_ID PRIMARY KEY (CATEGORY_ID);
ALTER TABLE DATE ADD CONSTRAINT PK_DATE_ID PRIMARY KEY (DATE_ID);
ALTER TABLE IMAGE ADD CONSTRAINT PK_IMAGE_ID PRIMARY KEY (IMAGE_ID);
ALTER TABLE PASSWORD ADD CONSTRAINT PK_PASSWORD_ID PRIMARY KEY (PASSWORD_ID);
ALTER TABLE PRICE ADD CONSTRAINT PK_PRICE_ID PRIMARY KEY (PRICE_ID);
ALTER TABLE PRODUCT ADD CONSTRAINT PK_PRODUCT_ID PRIMARY KEY (PRODUCT_ID);
ALTER TABLE PRODUCT ADD CONSTRAINT FK_PRODUCT_CATEGORY_ID FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY (CATEGORY_ID);
ALTER TABLE PRODUCT ADD CONSTRAINT FK_PRODUCT_PRICE_ID FOREIGN KEY (PRICE_ID) REFERENCES PRICE (PRICE_ID);
ALTER TABLE PRODUCT ADD CONSTRAINT FK_PRODUCT_IMAGE_ID FOREIGN KEY (IMAGE_ID) REFERENCES IMAGE (IMAGE_ID);
ALTER TABLE PURCHASE ADD CONSTRAINT PK_PURCHASE_ID PRIMARY KEY (PURCHASE_ID);
ALTER TABLE PURCHASE ADD CONSTRAINT FK_PURCHASE_USER_ID FOREIGN KEY (USER_ID) REFERENCES USER (USER_ID);
ALTER TABLE PURCHASE ADD CONSTRAINT FK_PURCHASE_PRODUCT_ID FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID);
ALTER TABLE PURCHASE ADD CONSTRAINT FK_PURCHASE_PRICE_ID FOREIGN KEY (PRICE_ID) REFERENCES PRICE (PRICE_ID);
ALTER TABLE PURCHASE ADD CONSTRAINT FK_PURCHASE_DATE_ID FOREIGN KEY (DATE_ID) REFERENCES DATE (DATE_ID);
ALTER TABLE PURCHASE ADD CONSTRAINT FK_PURCHASE_STATUS_ID FOREIGN KEY (STATUS_ID) REFERENCES STATUS (STATUS_ID);
ALTER TABLE ROLE ADD CONSTRAINT PK_ROLE_ID PRIMARY KEY (ROLE_ID);
ALTER TABLE STATUS ADD CONSTRAINT PK_STATUS_ID PRIMARY KEY (STATUS_ID);
ALTER TABLE USER ADD CONSTRAINT PK_USER_ID PRIMARY KEY (USER_ID);
ALTER TABLE USER ADD CONSTRAINT FK_USER_ROLE_ID FOREIGN KEY (ROLE_ID) REFERENCES ROLE (ROLE_ID);
ALTER TABLE USER ADD CONSTRAINT FK_USER_PASSWORD_ID FOREIGN KEY (PASSWORD_ID) REFERENCES PASSWORD (PASSWORD_ID);